// *******************************************************************************
// Assembly         : Bamanna.DouDian.Infrastructure.Modules.Core
// Author           : Generated From - EnumTypeTemplate
// Created          : 2016-11-02 11:41:15
//
// Last Modified By : T4
// Last Modified On : 2016-11-10 06:07:09
// 
// This file was generated by T4 code generator.
// Never edit this file!（请勿编辑此文件！此文件在每次生成后都会被覆盖。）
// If want to extend this class please use partial class. （如果想扩展此类请通过partial方式）。
//
// Generated by T4 Version # (1.0.0.0) on 2016-11-10 06:07:09
//
// *******************************************************************************
// <copyright file="EnumModule.auto.cs" company="Unify">
//     Copyright ©  2016
// </copyright>
// 
// <summary></summary>
// *******************************************************************************

using System;
using System.Runtime.Serialization;
using Bamanna.DouDian.Infrastructure.Attributes;
using Bamanna.DouDian.Infrastructure.Types;

namespace Bamanna.DouDian.Infrastructure.Modules
{
    /// <summary>
    /// 枚举模块
    /// </summary>
    [DataContract]
    [EnumType(DisplayName = "枚举模块", Name = "EnumModule", EnumType = EnumType.Sequence)]
    public enum EnumModule
    {
        /// <summary>
        /// 默认模块
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "默认模块", Name = "Default", IsDefault = true)]
        Default = 1,
        /// <summary>
        /// 业务模块
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "业务模块", Name = "Biz", IsDefault = false)]
        Biz = 2,

        // *******************************************************************************
        // End auto generation by T4(EnumModule.auto.cs) on 2016-11-10 06:07:09.
        // *******************************************************************************

    }
}

