
// *******************************************************************************
// Assembly         : C:\Users\smock\source\repos\NY-BAIS-API\Infrastructure\Bamanna.DouDian.Infrastructure.Modules\Bamanna.DouDian.Infrastructure.Modules
// Author           : Generated From - EnumDictColTemplate
// Created          : 2019-01-29 15:11:37
//
// Last Modified By : T4
// Last Modified On : 2019-01-29 15:11:37
// 
// This file was generated by T4 code generator.
// Never edit this file!（请勿编辑此文件！此文件在每次生成后都会被覆盖。）
// If want to extend this class please use partial class. （如果想扩展此类请通过partial方式）。
//
// Generated by T4 Version # (1.0.0.0) on 2019-01-29 15:11:37
//
// *******************************************************************************
// <copyright file="EnumDictCol.auto.cs" powerby="Unify">
//     Copyright ©  2018
// </copyright>
// 
// <summary></summary>
// *******************************************************************************


using Bamanna.DouDian.Infrastructure.Types;

namespace Bamanna.DouDian.Infrastructure.Modules.Common
{
    public partial class EnumDictCol
    {
        static EnumDictCol()
        {
            //to add auto
            // SetEnumDict<EnumType>();

            SetEnumDict<Languages>();

            SetEnumDict<HttpType>();
            // *******************************************************************************
            // End auto generation by T4(EnumDictCol.auto.cs) on 2019-01-29 15:11:37.
            // *******************************************************************************


            InitEnumDictCol();
        }
    }
}

