
// *******************************************************************************
// Assembly         : C:\Users\smock\source\repos\NY-BAIS-API\Infrastructure\Bamanna.DouDian.Infrastructure.Modules\Bamanna.DouDian.Infrastructure.Modules
// Author           : Generated From - EnumTypeTemplate
// Created          : 2019-01-29 15:11:37
//
// Last Modified By : T4
// Last Modified On : 2019-01-29 15:11:37
// 
// This file was generated by T4 code generator.
// Never edit this file!（请勿编辑此文件！此文件在每次生成后都会被覆盖。）
// If want to extend this class please use partial class. （如果想扩展此类请通过partial方式）。
//
// Generated by T4 Version # (1.0.0.0) on 2019-01-29 15:11:37
//
// *******************************************************************************
// <copyright file="HttpType.auto.cs" powerby="Unify">
//     Copyright ©  2018
// </copyright>
// 
// <summary></summary>
// *******************************************************************************


using System;
using System.Runtime.Serialization;
using Bamanna.DouDian.Infrastructure.Attributes;
using Bamanna.DouDian.Infrastructure.Types;

namespace Bamanna.DouDian.Infrastructure.Modules
{
    /// <summary>
    /// Http类型
    /// </summary>

    [DataContract]
    [EnumType(DisplayName = "Http类型", Name = "HttpType", EnumType = EnumType.Sequence)]
    public enum HttpType
    {

        /// <summary>
        /// GET
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "GET", Name = "GET", IsDefault = true)]
        GET = 1,

        /// <summary>
        /// PUT
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "PUT", Name = "PUT", IsDefault = false)]
        PUT = 2,

        /// <summary>
        /// DELETE
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "DELETE", Name = "DELETE", IsDefault = false)]
        DELETE = 3,

        /// <summary>
        /// POST
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "POST", Name = "POST", IsDefault = false)]
        POST = 4,


        // *******************************************************************************
        // End auto generation by T4(HttpType.auto.cs) on 2019-01-29 15:11:37.
        // *******************************************************************************


    }
}

