
// *******************************************************************************
// Assembly         : C:\Users\smock\source\repos\NY-BAIS-API\Infrastructure\Bamanna.DouDian.Infrastructure.Modules\Bamanna.DouDian.Infrastructure.Modules
// Author           : Generated From - EnumTypeTemplate
// Created          : 2019-01-29 15:11:37
//
// Last Modified By : T4
// Last Modified On : 2019-01-29 15:11:37
// 
// This file was generated by T4 code generator.
// Never edit this file!（请勿编辑此文件！此文件在每次生成后都会被覆盖。）
// If want to extend this class please use partial class. （如果想扩展此类请通过partial方式）。
//
// Generated by T4 Version # (1.0.0.0) on 2019-01-29 15:11:37
//
// *******************************************************************************
// <copyright file="Languages.auto.cs" powerby="Unify">
//     Copyright ©  2018
// </copyright>
// 
// <summary></summary>
// *******************************************************************************


using System;
using System.Runtime.Serialization;
using Bamanna.DouDian.Infrastructure.Attributes;
using Bamanna.DouDian.Infrastructure.Types;

namespace Bamanna.DouDian.Infrastructure.Modules
{
    /// <summary>
    /// 语言
    /// </summary>

    [DataContract]
    [EnumType(DisplayName = "语言", Name = "Languages", EnumType = EnumType.Sequence)]
    public enum Languages
    {

        /// <summary>
        /// 英文
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "英文", Name = "en", IsDefault = true)]
        en = 1,

        /// <summary>
        /// 中文
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "中文", Name = "zhCN", IsDefault = false)]
        zhCN = 2,

        /// <summary>
        /// 中国-繁体
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "中文-繁体", Name = "zhTW", IsDefault = false)]
        zhTW = 3,

        [EnumMember]
        [EnumValue(DisplayName = "日文", Name = "jaJp", IsDefault = false)]
        jaJp = 4,

        [EnumMember]
        [EnumValue(DisplayName = "韩语", Name = "koKr", IsDefault = false)]
        koKr = 5,
    }
}

