// *******************************************************************************
// Assembly         : Bamanna.DouDian.Infrastructure.Modules.Core
// Author           : Generated From - EnumTypeTemplate
// Created          : 2016-11-04 04:41:10
//
// Last Modified By : T4
// Last Modified On : 2016-11-17 11:13:23
// 
// This file was generated by T4 code generator.
// Never edit this file!（请勿编辑此文件！此文件在每次生成后都会被覆盖。）
// If want to extend this class please use partial class. （如果想扩展此类请通过partial方式）。
//
// Generated by T4 Version # (1.0.0.0) on 2016-11-17 11:13:23
//
// *******************************************************************************
// <copyright file="ResourceType.auto.cs" company="Unify">
//     Copyright ©  2016
// </copyright>
// 
// <summary></summary>
// *******************************************************************************

using System;
using System.Runtime.Serialization;
using Bamanna.DouDian.Infrastructure.Attributes;
using Bamanna.DouDian.Infrastructure.Types;

namespace Bamanna.DouDian.Infrastructure.Modules
{
    /// <summary>
    /// 资源类型
    /// </summary>
    [DataContract]
    [EnumType(DisplayName = "资源类型", Name = "ResourceType", EnumType = EnumType.Sequence)]
    public enum ResourceType
    {
        /// <summary>
        /// 系统
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "系统", Name = "System", IsDefault = false)]
        System = 1,
        /// <summary>
        /// 模块
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "模块", Name = "Module", IsDefault = false)]
        Module = 2,
        /// <summary>
        /// 页面
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "页面", Name = "Page", IsDefault = true)]
        Page = 3,
        /// <summary>
        /// 操作
        /// </summary>
        [EnumMember]
        [EnumValue(DisplayName = "操作", Name = "Action", IsDefault = false)]
        Action = 4,

        // *******************************************************************************
        // End auto generation by T4(ResourceType.auto.cs) on 2016-11-17 11:13:23.
        // *******************************************************************************


    }
}

